### PR TITLE
Mathlibcleanup

### PR DESCRIPTION
**Pull request by saadrahim**

### CODE REVIEW

**Comment by saadrahim** [comment]
Cleaning up libraries documentation. Some libraries need to have more consistent documentation in readthedocs. Internal tickets will be needed to prioritize that work.

**Review by Rmalavally — APPROVED** [review]
Reviewed the links to the user guide. Thanks for the updates.

**Comment by saadrahim** [comment]
Probably should get @pfultz2 to review for the MIGraphX line I changed just to be consistent with the math libraries.

**Review by doctorcolinsmith — APPROVED** [review]

**Review by pfultz2 — APPROVED** [review]
This looks good. Thanks!

**Pull request merged**
